services:
  piston:
    image: ghcr.io/engineer-man/piston:latest
    container_name: codefusion-piston
    restart: unless-stopped
    privileged: true
    ports:
      - "2000:2000"
    volumes:
      - piston-data:/piston

volumes:
  piston-data:
