version: "3.8"

services:
  piston:
    image: ghcr.io/engineer-man/piston:latest
    container_name: piston_api
    privileged: true
    restart: unless-stopped

    ports:
      - "2000:2000"

    tmpfs:
      - /tmp:exec